✈️ Phase 1: Data Loading & Understanding
Objective

Before cleaning or analyzing the data, we need to understand:

What information the dataset contains.
Whether there are missing values.
Whether there are duplicate records.
What each column represents.
Whether the data types are correct.
Whether any preprocessing is required.

Flight_Delay_Root_Cause_Analysis/


│
├── Dataset/
│     Airline_Delay_Cause.csv
│
├── Python/
│     01_Data_Loading.ipynb
│
└── README.md

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_column", None)
pd.set_option("display.max_rows",10)

print("Libraries Imported Succesfully")

Libraries Imported Succesfully

In [3]:
df = pd.read_csv("Airline_Delay_Cause.csv")
print("Data loaded Succesfully")

Data loaded Succesfully

In [5]:
df.head(3)

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2025,1,G4,Allegiant Air,ELM,"Elmira/Corning, NY: Elmira/Corning Regional",30.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2025,1,G4,Allegiant Air,ELP,"El Paso, TX: El Paso International",2.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2025,1,G4,Allegiant Air,EUG,"Eugene, OR: Mahlon Sweet Field",28.0,8.0,3.74,0.0,1.6,0.0,2.66,2.0,0.0,409.0,236.0,0.0,70.0,0.0,103.0

In [6]:
print("Number of Rows :", df.shape[0])
print("Number of Columns :", df.shape[1])

Number of Rows : 398233
Number of Columns : 21

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398233 entries, 0 to 398232
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 398233 non-null  int64
 1   month                398233 non-null  int64
 2   carrier              398233 non-null  object
 3   carrier_name         398233 non-null  object
 4   airport              398233 non-null  object
 5   airport_name         398233 non-null  object
 6   arr_flights          397576 non-null  float64
 7   arr_del15            397283 non-null  float64
 8   carrier_ct           397576 non-null  float64
 9   weather_ct           397576 non-null  float64
 10  nas_ct               397576 non-null  float64
 11  security_ct          397576 non-null  float64
 12  late_aircraft_ct     397576 non-null  float64
 13  arr_cancelled        397576 non-null  float64
 14  arr_diverted         397576 non-null  float64
 15  arr_delay            397576 non-null  float64
 16  carrier_delay        397576 non-null  float64
 17  weather_delay        397576 non-null  float64
 18  nas_delay            397576 non-null  float64
 19  security_delay       397576 non-null  float64
 20  late_aircraft_delay  397576 non-null  float64
dtypes: float64(15), int64(2), object(4)
memory usage: 63.8+ MB

In [9]:
print(df.columns.tolist())

['year', 'month', 'carrier', 'carrier_name', 'airport', 'airport_name', 'arr_flights', 'arr_del15', 'carrier_ct', 'weather_ct', 'nas_ct', 'security_ct', 'late_aircraft_ct', 'arr_cancelled', 'arr_diverted', 'arr_delay', 'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']

In [10]:
missing = df.isnull().sum()

missing[missing > 0]

arr_flights            657
arr_del15              950
carrier_ct             657
weather_ct             657
nas_ct                 657
                      ...
carrier_delay          657
weather_delay          657
nas_delay              657
security_delay         657
late_aircraft_delay    657
Length: 15, dtype: int64

In [11]:
missing_percentage = (
    df.isnull().sum() / len(df)
) * 100

missing_percentage.sort_values(ascending=False)

arr_del15       0.238554
weather_ct      0.164979
carrier_ct      0.164979
arr_flights     0.164979
security_ct     0.164979
                  ...
month           0.000000
year            0.000000
carrier_name    0.000000
carrier         0.000000
airport_name    0.000000
Length: 21, dtype: float64

In [12]:
duplicates = df.duplicated().sum()

print("Duplicate Records :", duplicates)

Duplicate Records : 0

In [14]:
df.describe()
df.describe(include="object")

,carrier,carrier_name,airport,airport_name
count,398233,398233,398233,398233
unique,38,51,425,449
top,OO,SkyWest Airlines Inc.,DTW,"Detroit, MI: Detroit Metro Wayne County"
freq,46212,46212,3688,3688

In [15]:
for column in df.columns:
    print(f"\n{column}")
    print(df[column].nunique())

year
23

month
12

carrier
38

carrier_name
51

airport
425

airport_name
449

arr_flights
7641

arr_del15
2407

carrier_ct
20129

weather_ct
5996

nas_ct
22659

security_ct
1219

late_aircraft_ct
24367

arr_cancelled
696

arr_diverted
142

arr_delay
31375

carrier_delay
16175

weather_delay
6049

nas_delay
15221

security_delay
715

late_aircraft_delay
19650

In [16]:
for column in df.columns:
    print(f"\n{column}")
    print(df[column].unique()[:10])

year
[2025 2024 2023 2022 2021 2020 2019 2018 2017 2016]

month
[ 1 12 11 10  9  8  7  6  5  4]

carrier
['G4' 'G7' 'HA' 'MQ' 'NK' 'OH' 'OO' 'PT' '9E' 'AA']

carrier_name
['Allegiant Air' 'GoJet Airlines LLC d/b/a United Express'
 'Hawaiian Airlines Network' 'Envoy Air' 'Spirit Airlines'
 'PSA Airlines Inc.' 'SkyWest Airlines Inc.' 'Piedmont Airlines'
 'Endeavor Air Inc.' 'American Airlines Network']

airport
['ELM' 'ELP' 'EUG' 'EVV' 'EWR' 'EYW' 'FAR' 'FAT' 'FCA' 'FLL']

airport_name
['Elmira/Corning, NY: Elmira/Corning Regional'
 'El Paso, TX: El Paso International' 'Eugene, OR: Mahlon Sweet Field'
 'Evansville, IN: Evansville Regional'
 'Newark, NJ: Newark Liberty International'
 'Key West, FL: Key West International' 'Fargo, ND: Hector International'
 'Fresno, CA: Fresno Yosemite International'
 'Kalispell, MT: Glacier Park International'
 'Fort Lauderdale, FL: Fort Lauderdale-Hollywood International']

arr_flights
[ 30.   2.  28.  18.  31.  73.  75.  39. 326. 138.]

arr_del15
[  0.   8.   1.   5.  12.   3. 104.  38.  17.  15.]

carrier_ct
[ 0.    3.74  2.17  4.69  4.34  1.55  1.   22.59  6.9   8.49]

weather_ct
[ 0.    1.    0.47 10.79  2.06  0.26  0.65  2.    1.89  0.48]

nas_ct
[ 0.    1.6   2.83  0.43  2.46  2.48 35.42  8.17  4.84  4.97]

security_ct
[0.   0.2  0.09 1.   0.8  0.78 0.45 0.55 0.14 0.86]

late_aircraft_ct
[ 0.    2.66  2.88  1.2   7.5   1.   35.2  20.87  3.4   3.02]

arr_cancelled
[ 0.  2.  1.  3.  6.  5.  9.  4. 12. 16.]

arr_diverted
[ 0.  1.  2.  3.  5. 12.  4. 18. 28.  7.]

arr_delay
[    0.   409.  1075.   446.   447.   468.   838.   440. 11093.  2191.]

carrier_delay
[   0.  236.  336.  129.  340.  140.  299. 3354.  269.  626.]

weather_delay
[   0. 1075.   21.   31. 2708.  110.   20.   26.  109.  204.]

nas_delay
[   0.   70.  110.   25.   90.  210. 2029.  502.  203.  169.]

security_delay
[ 0.  3. 15. 68. 76. 96.  9. 21. 28.  5.]

late_aircraft_delay
[   0.  103.  293.   38.  467.  110. 3002. 1310.  187.  223.]

✅ Phase 2 — Data Cleaning
Objective

Prepare the dataset for analysis by handling missing values, standardizing columns, optimizing data types, and creating a clean version for SQL and Power BI.

In [17]:
# Create a copy of the dataset
df_clean = df.copy()

In [18]:
missing = df_clean.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

arr_del15              950
weather_ct             657
carrier_ct             657
arr_flights            657
security_ct            657
                      ...
nas_ct                 657
late_aircraft_ct       657
arr_cancelled          657
late_aircraft_delay    657
nas_delay              657
Length: 15, dtype: int64

In [19]:
df_clean.dropna(inplace=True)

print(df_clean.shape)

(397283, 21)

In [20]:
df_clean.isnull().sum().sum()

np.int64(0)

In [21]:
df_clean.duplicated().sum()

np.int64(0)

In [22]:
df_clean.rename(columns={
    "carrier":"Airline_Code",
    "carrier_name":"Airline",
    "airport":"Airport_Code",
    "airport_name":"Airport",
    "arr_flights":"Total_Flights",
    "arr_del15":"Delayed_Flights",
    "carrier_ct":"Carrier_Delay_Count",
    "weather_ct":"Weather_Delay_Count",
    "nas_ct":"NAS_Delay_Count",
    "security_ct":"Security_Delay_Count",
    "late_aircraft_ct":"Late_Aircraft_Delay_Count",
    "arr_cancelled":"Cancelled_Flights",
    "arr_diverted":"Diverted_Flights",
    "arr_delay":"Total_Delay_Minutes",
    "carrier_delay":"Carrier_Delay_Minutes",
    "weather_delay":"Weather_Delay_Minutes",
    "nas_delay":"NAS_Delay_Minutes",
    "security_delay":"Security_Delay_Minutes",
    "late_aircraft_delay":"Late_Aircraft_Delay_Minutes"
}, inplace=True)

In [23]:
count_columns = [
    "Total_Flights",
    "Delayed_Flights",
    "Cancelled_Flights",
    "Diverted_Flights"
]

df_clean[count_columns] = df_clean[count_columns].astype("int64")

In [24]:
numeric_columns = df_clean.select_dtypes(include=["number"]).columns

(df_clean[numeric_columns] < 0).sum()

year                           0
month                          0
Total_Flights                  0
Delayed_Flights                0
Carrier_Delay_Count            0
                              ..
Carrier_Delay_Minutes          0
Weather_Delay_Minutes          0
NAS_Delay_Minutes              2
Security_Delay_Minutes         0
Late_Aircraft_Delay_Minutes    0
Length: 17, dtype: int64

In [25]:
# Find rows with negative values
negative_rows = df_clean[df_clean["NAS_Delay_Minutes"] < 0]

negative_rows

,year,month,Airline_Code,Airline,Airport_Code,Airport,Total_Flights,Delayed_Flights,Carrier_Delay_Count,Weather_Delay_Count,NAS_Delay_Count,Security_Delay_Count,Late_Aircraft_Delay_Count,Cancelled_Flights,Diverted_Flights,Total_Delay_Minutes,Carrier_Delay_Minutes,Weather_Delay_Minutes,NAS_Delay_Minutes,Security_Delay_Minutes,Late_Aircraft_Delay_Minutes
375209,2004,11,EV,Atlantic Southeast Airlines,BWI,"Baltimore, MD: Baltimore/Washington Internatio...",30,7,3.51,3.51,-0.01,0.00,0.00,0,0,414.0,199.0,216.0,-1.0,0.0,0.0
394641,2003,8,B6,JetBlue Airways,SLC,"Salt Lake City, UT: Salt Lake City International",62,11,5.22,0.79,0.66,0.07,4.25,0,0,1097.0,660.0,93.0,-19.0,10.0,353.0

In [26]:
numeric_columns = df_clean.select_dtypes(include=["number"]).columns

for col in numeric_columns:
    count = (df_clean[col] < 0).sum()
    if count > 0:
        print(f"{col}: {count}")

NAS_Delay_Count: 1
NAS_Delay_Minutes: 2

In [27]:
df_clean = df_clean[df_clean["NAS_Delay_Minutes"] >= 0]

print(df_clean.shape)

(397281, 21)

In [28]:
(df_clean.select_dtypes(include="number") < 0).sum()

year                           0
month                          0
Total_Flights                  0
Delayed_Flights                0
Carrier_Delay_Count            0
                              ..
Carrier_Delay_Minutes          0
Weather_Delay_Minutes          0
NAS_Delay_Minutes              0
Security_Delay_Minutes         0
Late_Aircraft_Delay_Minutes    0
Length: 17, dtype: int64

In [30]:
df_clean.to_csv(
    "Cleaned_Airline_Delay.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!